
version: '2.4.1'
services:
  ShangJiao_m3u8_web:
    image: nginx:latest
    volumes:
        - ./nginx/video:/usr/share/nginx/video
        - ./nginx/mock_live:/usr/share/nginx/mocklive:ro
        - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "6789:80"
    restart: always
  MockLive:
    image: ratuliit42/ffmpeg4.0.2-netcore-v2.1:latest
    volumes:
        - ./nginx/mock_live:/mock_live:rw
    working_dir: /mock_live
#    command: ffmpeg -re -stream_loop -1 -i  jay.mp4 -c copy  -f ssegment -segment_format mpegts -segment_time 2  -segment_list_size 6 -hls_wrap 10 -segment_list ./playlist.m3u8  ./segment-%04d.ts
    command: sh -c "find . -name 'segment-*.ts' -type f -delete; \
                ffmpeg -re -stream_loop -1 -i jay.mp4 -c copy -f ssegment \
                -segment_format mpegts -segment_time 2 -segment_list_size 6 \
                -hls_wrap 10 -segment_list ./playlist.m3u8 ./segment-%04d.ts"

